<a href="https://colab.research.google.com/github/151ali/lr-pytorch/blob/main/11_einsum_notation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.randn((2,3))

In [3]:
x

tensor([[ 0.6830, -0.0255,  0.4464],
        [-1.0930, -0.1813,  1.9189]])

In [4]:
# permutation
torch.einsum("ij->ji",x)

tensor([[ 0.6830, -1.0930],
        [-0.0255, -0.1813],
        [ 0.4464,  1.9189]])

In [5]:
# summation over all elements
torch.einsum("ij->",x)

tensor(1.7485)

In [6]:
# summation over colulmns
torch.einsum("ij->j",x)

tensor([-0.4100, -0.2068,  2.3653])

In [7]:
# summation over rows
torch.einsum("ij->i",x)

tensor([1.1039, 0.6446])

In [8]:
# matrix-vector multiplication
v = torch.ones((1, 3))
torch.einsum("ij,kj->ik",x,v)

tensor([[1.1039],
        [0.6446]])

In [9]:
# matrix-matrix multiplication
print(x.mm(x.t()))

print(torch.einsum("ij,kj->ik",x,x))

tensor([[0.6664, 0.1147],
        [0.1147, 4.9097]])
tensor([[0.6664, 0.1147],
        [0.1147, 4.9097]])


In [11]:
# dot product first row first row
torch.einsum("i,i->",x[0],x[0])

tensor(0.6664)

In [12]:
# dot product with matrix
torch.einsum("ij,ij->",x,x)

tensor(5.5760)

In [13]:
# element wise multiplication
torch.einsum("ij,ij->ij",x,x)

tensor([[4.6647e-01, 6.4826e-04, 1.9924e-01],
        [1.1946e+00, 3.2883e-02, 3.6822e+00]])

In [15]:
# outer product
a = torch.rand(3)
b = torch.rand(5)
print(a)
print(b)
torch.einsum("i,j->ij",a,b)

tensor([0.1293, 0.6494, 0.8905])
tensor([0.0744, 0.1077, 0.0300, 0.8260, 0.2980])


tensor([[0.0096, 0.0139, 0.0039, 0.1068, 0.0385],
        [0.0483, 0.0699, 0.0195, 0.5364, 0.1935],
        [0.0662, 0.0959, 0.0267, 0.7355, 0.2653]])

In [16]:
# batch matrix multiplication

a = torch.rand((3,2,5))
b = torch.rand((3,5,3))


torch.einsum("ijk,ikl->ijl",a,b)


tensor([[[0.9618, 1.1736, 1.1913],
         [1.5092, 1.0194, 1.4541]],

        [[1.0644, 0.7327, 1.5274],
         [0.9358, 0.6952, 1.4867]],

        [[1.7032, 1.2922, 1.5196],
         [1.0232, 0.7781, 0.8178]]])

In [22]:
# matrix diagonal
a = torch.rand((2,2))

print(a)

torch.einsum("ii->i",a)


tensor([[0.5349, 0.9614],
        [0.6673, 0.6055]])


tensor([0.5349, 0.6055])

In [28]:
# matrix trace
a = torch.rand((2,2))

print(a)

torch.einsum("ii->",a)

tensor([[0.6304, 0.3092],
        [0.7677, 0.7676]])


tensor(1.3980)

[EINSUM IS ALL YOU NEED - EINSTEIN SUMMATION IN DEEP LEARNING](https://https://rockt.github.io/2018/04/30/einsum)